config/routes.rb
Cob::Application.routes.draw do
  resources :animals

  mount Ckeditor::Engine => '/ckeditor'

	resources "users"
  
  resources "user_sessions"
  
  resources "events"
  
  resources :departments do
    collection do 
      post :sort
    end
    resources :contacts
  end
  
  resources :resources do
    collection do 
      post :sort
    end
  end
  
  resources "rescats"
  
  match 'new_contact' =>  'contact_us#new', :conditions => { :method => :get }
  resources :contact_us, :only => [:new, :create]

  resources :faqs do
    collection do
      post :sort
    end
  end

  resources "faq_categories"
  
  resources "showcase_medias"
  resources "showcase_images"
  
  resources :showcases do
    collection do 
      post :sort
    end
    resources :showcase_images
    resources :showcase_medias
  end

  	match 'login' => "user_sessions#new",      :as => :login
  	match 'logout' => "user_sessions#destroy", :as => :logout
	  
	 	root :to => "dash#index"

end

app/models/faq_category.rb
class FaqCategory < ActiveRecord::Base
	has_and_belongs_to_many :faqs, :order=>"position ASC"
	attr_accessible :category
end

app/controllers/faq_categories_controller.rb
class FaqCategoriesController < ApplicationController
  # GET /faq_categories
  # GET /faq_categories.xml
  def index
    @faq_categories = FaqCategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @faq_categories }
    end
  end

  # GET /faq_categories/1
  # GET /faq_categories/1.xml
  def show
    @faq_category = FaqCategory.find(params[:id])
    @faqs = @category.faqs

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @faq_category }
    end
  end

  # GET /faq_categories/new
  # GET /faq_categories/new.xml
  def new
    @faq_category = FaqCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @faq_category }
    end
  end

  # GET /faq_categories/1/edit
  def edit
    @faq_category = FaqCategory.find(params[:id])
  end

  # POST /faq_categories
  # POST /faq_categories.xml
  def create
    @faq_category = FaqCategory.new(params[:faq_category])

    respond_to do |format|
      if @faq_category.save
        flash[:notice] = 'FaqCategory was successfully created.'
        format.html { redirect_to faq_categories_path }
        format.xml  { render :xml => @faq_category, :status => :created, :location => @faq_category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @faq_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /faq_categories/1
  # PUT /faq_categories/1.xml
  def update
    @faq_category = FaqCategory.find(params[:id])

    respond_to do |format|
      if @faq_category.update_attributes(params[:faq_category])
        flash[:notice] = 'FaqCategory was successfully updated.'
        format.html { redirect_to faq_categories_path }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @faq_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /faq_categories/1
  # DELETE /faq_categories/1.xml
  def destroy
    @faq_category = FaqCategory.find(params[:id])
    @faq_category.destroy

    respond_to do |format|
      format.html { redirect_to(faq_categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/faq_categories_helper.rb
module FaqCategoriesHelper
end

app/views/faq_categories/edit.html.erb
<div id="middleCol">
<h1>Editing FAQ Categories</h1>

<%= form_for(@faq_category) do |f| %>
<% if @faq_category.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@faq_category.errors.count, "error") %> prohibited this event from being saved:</h2>

    <ul>
    <% @faq_category.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
  <p>
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Back', faq_categories_path, :class=>"admin" %>
</div>

app/views/faq_categories/index.html.erb
<div id="middleCol">
<h1>Listing FAQ Categories</h1>
<p><%= link_to 'New FAQ Category', new_faq_category_path, :class=>'admin' %> 
<%= link_to 'FAQ List', faqs_path, :class=>'admin' %></p>
<table>
  <tr>
    <th></th>
   	<th></th>
    <th>Category</th>
  </tr>

<% @faq_categories.each do |faq_category| %>
  <tr class="<%= cycle('even', 'odd') %>">
    <td><%= link_to 'Edit', edit_faq_category_path(faq_category), :class=>'admin' %></td>
    <td><%= link_to 'Delete', faq_category, :confirm => 'Are you sure?', :method => :delete, :class=>'admin' %></td>
    <td><%=h faq_category.category %></td>
  </tr>
<% end %>
</table>
</div>
<div id="rightCol">
</div>

app/views/faq_categories/new.html.erb
<div id="middleCol">
<h1>New FAQ Category</h1>

<%= form_for(@faq_category) do |f| %>
  <p>
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', faq_categories_path, :class=>"admin" %>
</div>
<div id="rightCol">
</div>

app/views/faq_categories/show.html.erb
<div id="middleCol">
<p>
  <b>Category:</b>
  <%=h @faq_category.category %>
</p>


<%= link_to 'Edit', edit_faq_category_path(@faq_category) %> |
<%= link_to 'Back', faq_categories_path %>
<div>