config/routes.rb
Cob::Application.routes.draw do
  resources :animals

  mount Ckeditor::Engine => '/ckeditor'

	resources "users"
  
  resources "user_sessions"
  
  resources "events"
  
  resources :departments do
    collection do 
      post :sort
    end
    resources :contacts
  end
  
  resources :resources do
    collection do 
      post :sort
    end
  end
  
  resources "rescats"
  
  match 'new_contact' =>  'contact_us#new', :conditions => { :method => :get }
  resources :contact_us, :only => [:new, :create]

  resources :faqs do
    collection do
      post :sort
    end
  end

  resources "faq_categories"
  
  resources "showcase_medias"
  resources "showcase_images"
  
  resources :showcases do
    collection do 
      post :sort
    end
    resources :showcase_images
    resources :showcase_medias
  end

  	match 'login' => "user_sessions#new",      :as => :login
  	match 'logout' => "user_sessions#destroy", :as => :logout
	  
	 	root :to => "dash#index"

end

app/models/faq.rb
class Faq < ActiveRecord::Base
	validates_presence_of :answer, :question 
	has_and_belongs_to_many :faq_categories
	belongs_to :department
	attr_accessible :featured, :url, :question, :answer, :department_id, :faq_category_ids
	acts_as_list
	
  include PgSearch
  pg_search_scope :search, :against => [:question, :answer], 
    :using  => {:tsearch  => {:dictionary => "english"}}
	
   	def self.text_search(query)
   	  if query.present?
        search(query)
      else
        scoped
      end
   	end
  
    # def self.search(search)
    #  if search
    #     search = search.to_s.downcase
    #     where(['lower(question) LIKE ? OR lower(answer) LIKE ?', "%#{search}%", "%#{search}%"]).order('position ASC')
    #   end
    # end

	def self.find_for_home
		where('featured = ?',true).order(:position)
	end

end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
	# collection_select bombs if validations run unless we define 
	# @departments here. Doesn't work in New and Edit when validations run
	# put it here instead of in the view (where it works also with validations)
	# This is the same as including the @departments in each of the listed actions
  before_filter :instantiate_departments, :only => [:index, :new, :edit, :create, :update]
	before_filter :check_auth, :only=>[:edit]
  
  def instantiate_departments
  	@departments = Department.find(:all, :order => 'dept_name asc')
  	@faq_categories=FaqCategory.order(:category)
  	@page_title = "#{@current_action.titleize} FAQs"
  end
  
  def sort
  	params[:faq].each_with_index do |id, index|
  		Faq.update_all(['position=?', index+1], ['id=?', id])
  	end
  	render :nothing=>true
  end
 
  #for listing faq categories on the show and index pages
  def get_dept_cat
    @faqs = Faq.find(:all, :include=> :department, :order => 'departments.id ASC, faqs.position ASC')
    @faq_dept = @faqs.group_by { |c| c.department }
    
  end
  
  # GET /faqs
  # GET /faqs.xml
  def index
    get_dept_cat
   	@page_title = "FAQs"
  	if params[:dept] and (params[:dept]) != ""
  		@dept = Department.find(params[:dept])
	    @faqs = @dept.faqs.order(:position)
	    @title_text= @dept.dept_name
  	  @blurb= (@faqs.size == 1 ? "There is 1 result." : "There are #{@faqs.size} results.")
 	    @page_title= @page_title + @title_text 
 	  elsif params[:cat]
    		@cat = FaqCategory.find(params[:cat])
  	    @faqs = @cat.faqs
  	    @title_text= @cat.category
    	  @blurb= (@faqs.size == 1 ? "There is 1 result." : "There are #{@faqs.size} results.")
   	    @page_title= @page_title + @title_text
 		elsif params[:query] and (params[:query] != "")
	  	@faqs = Faq.text_search(params[:query])
	    @title_text='Search Results'
  	  @blurb= (@faqs.size == 1 ? "There is 1 result." : "There are #{@faqs.size} results.")
 	    @page_title= @page_title + @title_text
 		else 
	  	@faqs = Faq.order(:position)
	    @title_text='All FAQs'
  	  @blurb= ''
    end
    if admin?
    	@cursor_style = 'cursor:move;' # show drag cursor on sortable list
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @faqs }
    end
  end

  # GET /faqs/1
  # GET /faqs/1.xml
  def show
    @faq = Faq.find(params[:id])
    get_dept_cat
  	@page_title = @faq.question

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @faq }
    end
  end

  # GET /faqs/new
  # GET /faqs/new.xml
  def new
    @faq = Faq.new
    @button_text = 'Create'

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @faq }
    end
  end

  # GET /faqs/1/edit
  def edit
    @faq = Faq.find(params[:id])
    @button_text = 'Update'
 end

  # POST /faqs
  # POST /faqs.xml
  def create
    @faq = Faq.new(params[:faq])

    respond_to do |format|
      if @faq.save
        flash[:notice] = 'Faq was successfully created.'
        format.html { redirect_to(@faq) }
        format.xml  { render :xml => @faq, :status => :created, :location => @faq }
      else
		    @button_text = 'Create'
        format.html { render :action => "new" }
        format.xml  { render :xml => @faq.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /faqs/1
  # PUT /faqs/1.xml
  def update
  	params[:faq][:faq_category_ids] ||= []
    @faq = Faq.find(params[:id])

    respond_to do |format|
      if @faq.update_attributes(params[:faq])
        flash[:notice] = 'Faq was successfully updated.'
        format.html { redirect_to(@faq) }
        format.xml  { head :ok }
      else
		    @button_text = 'Update'
        format.html { render :action => "edit" }
        format.xml  { render :xml => @faq.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /faqs/1
  # DELETE /faqs/1.xml
  def destroy
    @faq = Faq.find(params[:id])
    @faq.destroy

    respond_to do |format|
      format.html { redirect_to(faqs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/views/faqs/_add_edit_faq.html.erb
<%= form_for(@faq) do |f| %>
<div id="middleCol">
	<% if @faq.errors.any? %>
	  <div id="error_explanation">
	    <h2><%= pluralize(@faqs.errors.count, "error") %> prohibited this event from being saved:</h2>
	    <ul>
	    <% @faqs.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
		<% end %>
	    </ul>
	  </div>
	<% end %>
  <p>
    <%= f.label :question %><br />
    <%= f.text_field :question, :size=> 40 %>
  </p>
  <p>
     <%= f.label :answer %><br />
   	 <%= f.cktext_area :answer, :toolbar=>'Basic2', :width=>'360px', :height=>'400px' %>  </p>
  </p>
  <p>
    <%= f.label :url %><br />
    <%= f.text_field :url, :size=> 40 %>
  </p>
  <p>
    <%= f.label 'Department' %><br />
		<%= collection_select(:faq, :department_id, @departments, :id, :dept_name) %>
  </p>
  <p>
    <%= f.label :featured %><br />
    <%= f.check_box :featured %>
  </p>
  <p>
    <%= f.submit @button_text %>
  </p>
  <p>
	<%= link_to 'Cancel', faqs_path, :class=>'admin' %>
  </p>	
</div>
<div id="rightCol">
	<div style="padding-left:10px;">
		 <h2 class="title">Select Categories</h2>
		 <% for cat in FaqCategory.find(:all) %>  
				 <div>  
					 <label><%= check_box_tag "faq[faq_category_ids][]", cat.id, @faq.faq_categories.include?(cat) %>  
					 <%= cat.category %></label>
				 </div>  
		 <% end %>
	</div>
</div>
<% end %>

app/views/faqs/_dept_list.html.erb
<h3 class="title">Departments</h3>
		<ul>
		<% @faq_dept.each do |dept, faqs| %>
			<li><%= link_to dept.dept_name, faqs_path(:anchor=>dept) %></li>
		<% end %>
		</ul>

app/views/faqs/_faq_list.html.erb
   <ul id="faqs">
   <% @faqs.each do |faq| %>  
    <li id="faq_<%= faq.id %>"> <%= link_to faq.question, faq %>
			<% if admin? %>
			<div>
			<span class="handle" style="<%= @cursor_style %>">DRAG</span>
			<%= link_to	'Edit', edit_faq_path(faq), :class => 'admin' %>  
			<%= link_to 'Delete', faq, :confirm => 'Are you sure?', :method => :delete, :class => 'admin'%>
			</div>
			<% end %>
		</li>
	<% end %>
  </ul>

<% content_for :javascript  do %>
  <%= javascript_tag do %>
    // Sorting the list

    $(document).ready(function(){
      $('#faqs').sortable({
        axis: 'y',
        dropOnEmpty: false,
        handle: '.handle',
        cursor: 'crosshair',
        items: 'li',
        opacity: 0.4,
        scroll: true,
        update: function(){
          $.ajax({
            type: 'post',
            data: $('#faqs').sortable('serialize'),
            dataType: 'script',
            complete: function(request){
              $('#faqs').effect('highlight');
              },
            url: '/faqs/sort'})
          }
        });
      });
  <% end %>
<% end %>

app/views/faqs/edit.html.erb
<h1>Editing FAQ</h1>

<%= render :partial => 'add_edit_faq' %>

app/views/faqs/edit1.html.erb
<h1>Editing faq</h1>

<% form_for(@faq) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :question %><br />
    <%= f.text_field :question %>
  </p>
  <p>
    <%= f.label :answer %><br />
    <%= f.text_area :answer %>
  </p>
  <p>
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.label :featured %><br />
    <%= f.check_box :featured %>
  </p>
  <p>
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </p>
  <p>
    <%= f.label :department_id %><br />
    <%= f.text_field :department_id %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @faq %> |
<%= link_to 'Back', faqs_path %>

app/views/faqs/index.html.erb
<div id="middleCol">
<h1>Frequently Asked Questions</h1>
<% if admin? %>
	<br />
	<%= link_to 'New FAQ', new_faq_path, :class => 'admin' %> 
	<%= link_to 'FAQ Categories', faq_categories_path, :class => 'admin' %>
<% end %>
<div>
	<%= form_tag faqs_path, :method => 'get' do %>
  <p>
    <label class="instructions"> Keyword Search</label><br />
    <%= text_field_tag :query, params[:query] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
	<% end %>
	<p class="instructions">Enter a search term, such as <tt><big>education</big></tt> or <tt><big>conference</big></tt>
	</p>
</div>

<% if params[:cat] || params[:dept] || params[:query] %>
	 <h2 class="monthDivider boxshadow"><%= @title_text %></h2> 
	<div class="instructions"><%== @blurb %> </div>
	<%= render :partial=>"faq_list" %>

<% else %>
	<% @faq_dept.each do |dept, @faqs| %>  
		<a name="<%= dept.id %>"></a>
	 <h2 class="monthDivider boxshadow"><%= dept.dept_name %></h2> 
	 		<%= render :partial=>"faq_list" %>
	<% end %> 
<% end %>
</div>
<div id="rightCol">
	<p><%= link_to "View All", faqs_path, :class => 'foot sidebar'%></p>

	<h3 class="title">FAQ Categories</h3>
	<span class="instructions">Click to Browse by Category</span>
			<ul class="pineapple">
			<% @faq_categories.each do |cat| %>
				<% unless cat.faqs.empty? %>
				<li><%= link_to cat.category, :action=>:index, :controller=>:faqs, :cat=>cat %></li>
				<% end %>
			<% end %>
			</ul>
</div>

app/views/faqs/index1.html.erb
<h1>Listing faqs</h1>

<table>
  <tr>
    <th>Question</th>
    <th>Answer</th>
    <th>Url</th>
    <th>Featured</th>
    <th>Position</th>
    <th>Department</th>
  </tr>

<% @faqs.each do |faq| %>
  <tr>
    <td><%=h faq.question %></td>
    <td><%=h faq.answer %></td>
    <td><%=h faq.url %></td>
    <td><%=h faq.featured %></td>
    <td><%=h faq.position %></td>
    <td><%=h faq.department_id %></td>
    <td><%= link_to 'Show', faq %></td>
    <td><%= link_to 'Edit', edit_faq_path(faq) %></td>
    <td><%= link_to 'Destroy', faq, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New faq', new_faq_path %>

app/views/faqs/new.html.erb
<%= render :partial => 'add_edit_faq' %>

app/views/faqs/new1.html.erb
<h1>New faq</h1>

<% form_for(@faq) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :question %><br />
    <%= f.text_field :question %>
  </p>
  <p>
    <%= f.label :answer %><br />
    <%= f.text_area :answer %>
  </p>
  <p>
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.label :featured %><br />
    <%= f.check_box :featured %>
  </p>
  <p>
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </p>
  <p>
    <%= f.label :department_id %><br />
    <%= f.text_field :department_id %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', faqs_path %>

app/views/faqs/show.html.erb
<div id="middleCol" class="wide">
	<h1>Frequently Asked Question:</h1>
		<div class="additional">Additional solutions can be found on each department's page</div><br />
		<div class="question"><%=h @faq.question %></div>
		<div class="answer"><%== @faq.answer %></div>

	<% if @faq.url.size > 0 %>
	<br /><br />
	<span class="instructions">Additional information is available at:  <%= link_to @faq.url, format_url(@faq.url) %></span>
	<% end %>
	<br /><br />
	<span class="list_date">posted <%= @faq.updated_at.strftime("%m-%d-%Y")  %>
		[<%= link_to @faq.department.dept_name, department_path(@faq.department) %>] </span> 
<% if auth?(@faq.department_id) %>
<br />
<%= link_to 'Edit', edit_faq_path(@faq), :class=>'admin' %> 
<%= link_to 'Back', faqs_path, :class=>'admin' %>
<% end %>
</div>

app/views/faqs/show1.html.erb
<p>
  <b>Question:</b>
  <%=h @faq.question %>
</p>

<p>
  <b>Answer:</b>
  <%=h @faq.answer %>
</p>

<p>
  <b>Url:</b>
  <%=h @faq.url %>
</p>

<p>
  <b>Featured:</b>
  <%=h @faq.featured %>
</p>

<p>
  <b>Position:</b>
  <%=h @faq.position %>
</p>

<p>
  <b>Department:</b>
  <%=h @faq.department_id %>
</p>


<%= link_to 'Edit', edit_faq_path(@faq) %> |
<%= link_to 'Back', faqs_path %>