config/routes.rb
Cob::Application.routes.draw do
  resources :animals

  mount Ckeditor::Engine => '/ckeditor'

	resources "users"
  
  resources "user_sessions"
  
  resources "events"
  
  resources :departments do
    collection do 
      post :sort
    end
    resources :contacts
  end
  
  resources :resources do
    collection do 
      post :sort
    end
  end
  
  resources "rescats"
  
  match 'new_contact' =>  'contact_us#new', :conditions => { :method => :get }
  resources :contact_us, :only => [:new, :create]

  resources :faqs do
    collection do
      post :sort
    end
  end

  resources "faq_categories"
  
  resources "showcase_medias"
  resources "showcase_images"
  
  resources :showcases do
    collection do 
      post :sort
    end
    resources :showcase_images
    resources :showcase_medias
  end

  	match 'login' => "user_sessions#new",      :as => :login
  	match 'logout' => "user_sessions#destroy", :as => :logout
	  
	 	root :to => "dash#index"

end

app/models/animal.rb
class Animal < ActiveRecord::Base
 has_attached_file :pic, :styles => { :tiny => "36x36#", :small => "72x72#", :medium => "190"}
   attr_accessible :ac_id, :adoptable, :age, :arrival_date, :breed, :description, :final_date, :location, :pic, :release_date, :sex, :species
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_attached_file :photo, :styles => { :tiny => "25x25#", :small => "72x72#", :medium => "100x111>", :large => "300x300>"}
	belongs_to :department
	
	acts_as_list :scope => :department
	
	attr_accessible :title, :lastname, :firstname, :email, :photo

end

app/models/contact_us.rb
class ContactUs

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  validates_presence_of :name, :message, :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  

  attr_accessor :name, :email, :message, :department_id

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end
end

app/models/department.rb
class Department < ActiveRecord::Base
	has_many :events
	has_many :faqs
	has_and_belongs_to_many :resources
	has_many :contacts
	has_and_belongs_to_many :users
  has_attached_file :pic, :styles => { :tiny => "25x25#", :small => "72x72#", :medium => "190"}
	attr_accessible :dept_fax, :description, :dept_name, :dept_email, :dept_location, :dept_mailing, :dept_phone, :dept_hours, :pic
	validates_presence_of :dept_name
	
	def self.get_contacts(dept)
		dept.contacts.find(:all, :order=>:position)
	end

end

app/models/event.rb
class Event < ActiveRecord::Base
 	belongs_to :department
 	attr_accessible :event_type, :start_date, :end_date, :title, :blurb, :description, :url, :department_id, :placement
 	
 	scope :department, where("placement = 'department' or placement = 'both'")
 	scope :home, where("placement = 'home' or placement = 'both'")
  scope :upcoming, where("end_date >= '#{Date.today}'").order('start_date asc')
  scope :news_type, where("event_type='News' AND start_date<='#{Date.today}'")
  scope :event_type, where("event_type='Event'")
 	
  def	self.find_for_home(event_type,order)
   	if event_type
   		this_condition = " AND event_type='#{event_type}'"
   		if event_type == 'News'
   			this_condition= "AND start_date<='#{Date.today}' " + this_condition
   		end
   	end
   	find(:all, :limit=>6, :order=>'start_date '+ order, :conditions=>"end_date >= '#{Date.today}' #{this_condition}" )
   end

   def	self.find_for_council(event_type)
    	if event_type
    		this_condition = " AND event_type='#{event_type}'"
    	end
    	find(:all, :limit=>6, :order=>'start_date ASC', :conditions=>"end_date >= '#{Date.today}' AND department_id=2 #{this_condition}" )
    end

end

app/models/faq.rb
class Faq < ActiveRecord::Base
	validates_presence_of :answer, :question 
	has_and_belongs_to_many :faq_categories
	belongs_to :department
	attr_accessible :featured, :url, :question, :answer, :department_id, :faq_category_ids
	acts_as_list
	
  include PgSearch
  pg_search_scope :search, :against => [:question, :answer], 
    :using  => {:tsearch  => {:dictionary => "english"}}
	
   	def self.text_search(query)
   	  if query.present?
        search(query)
      else
        scoped
      end
   	end
  
    # def self.search(search)
    #  if search
    #     search = search.to_s.downcase
    #     where(['lower(question) LIKE ? OR lower(answer) LIKE ?', "%#{search}%", "%#{search}%"]).order('position ASC')
    #   end
    # end

	def self.find_for_home
		where('featured = ?',true).order(:position)
	end

end

app/models/faq_category.rb
class FaqCategory < ActiveRecord::Base
	has_and_belongs_to_many :faqs, :order=>"position ASC"
	attr_accessible :category
end

app/models/rescat.rb
class Rescat < ActiveRecord::Base
  has_and_belongs_to_many :resources, :order=>"position asc, resource_type ASC, title asc"
	validates_presence_of :category
	attr_accessible :category, :blurb

end

app/models/resource.rb
class Resource < ActiveRecord::Base
  has_attached_file :res 
	has_and_belongs_to_many :rescats
	has_and_belongs_to_many :departments, :order=>"dept_name asc"
	
  validates_presence_of :res_file_name, :message => "( Document/URL ) cannot be empty"
  validates_presence_of :title
	acts_as_list
  
 	scope :featured, where(:featured => true)

  attr_accessible :title, :description, :featured, :department_ids, :rescat_ids, :res, :resource_type, :res_file_name
 # this before filter and associated function is supposed to allow the upload of a non-image file
	before_post_process :image?
 
	def image?
		!(res_content_type =~ /^image.*/).nil?
	end
	
  include PgSearch
  pg_search_scope :search, :against => [:title, :description], 
    :using  => {:tsearch  => {:dictionary => "english"}}
	
    # def self.search(search)
    #   if search
    #     search = search.to_s.downcase
    #     where(['lower(title) LIKE ? OR lower(description) LIKE ?', "%#{search}%", "%#{search}%"]).order('position asc')
    #   #else
    #   # find(:all)
    #   end
    # end

   	def self.find_for_home
   		where('featured = ?',true).order(:position).limit(10)
   	end

   	def self.text_search(query)
   	  if query.present?
        search(query)
      else
        scoped
      end
   	end	
end

app/models/showcase.rb
class Showcase < ActiveRecord::Base
  has_attached_file :photo, :styles => { :tiny => "25x25#", :small => "72x72#", :medium => "150x150>", :large => "300x300>"}
  has_many :showcase_images, :order => :position
  has_many :showcase_medias
  validates_presence_of :title
  
  attr_accessible :title, :blurb, :published, :sidebar, :article, :publish_date, :photo

  scope :published, where(:published => true).order('publish_date desc')
  def	self.find_for_home
  	#find(:all, :limit=>1, :order=>'publish_date desc', :conditions=>"published = 'true'" )
  	where("published= ?", true).limit(1).order('publish_date desc')
  end
end

app/models/showcase_image.rb
class ShowcaseImage < ActiveRecord::Base
  has_attached_file :photo, :styles => { :tiny => "25x25#", :small => "72x72#", :medium => "150x150>"}
  belongs_to :showcase
  validates_presence_of :photo_file_name
  
  acts_as_list :scope => :showcase
  
  attr_accessible :photo, :caption
end

app/models/showcase_media.rb
class ShowcaseMedia < ActiveRecord::Base
  has_attached_file :media
  belongs_to :showcase
  validates_presence_of :media_file_name
  
  attr_accessible :media, :caption
 # this before filter and associated function is supposed to allow the upload of a non-image file
	before_post_process :image?
 
	def image?
		!(media_content_type =~ /^image.*/).nil?
	end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_and_belongs_to_many :departments
	acts_as_authentic
	attr_accessible :admin_level, :name, :password_confirmation, :login, :password, :department_ids
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/dash_controller.rb
class DashController < ApplicationController
	def index
    if admin?
    	@cursor_style = 'cursor:move;' # show drag cursor on sortable list
    end
    @page_title = "County Government Information for Branch County, Michigan"
		@faqs= Faq.find_for_home
  	@events = Event.upcoming.event_type.home
  	@news = Event.upcoming.news_type.home
  	@resources = Resource.find_for_home
    @showcase = Showcase.find_for_home.first
		
	end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dash_helper.rb
module DashHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/rescats_helper.rb
module RescatsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/views/dash/index.html.erb
<div id="middleCol">
	<div class="pageHeader">Welcome to Branch County</div>
	<h2>Common Solutions</h2> 
	<%= render :partial => "faqs/faq_list" %>
		<%= link_to "View All FAQs...", faqs_path, :class=>'foot' %>
		<% if @news.any?%>
		<h2>Announcements</h2> 
			 <ul>
			 <% @news.each do |news| %>  
				<li><%= link_to news.title, news %></li>
					<% if admin? %>
						<dd><%= link_to	'Edit', edit_event_path(news), :class => 'admin' %>  
						<%= link_to 'Delete', news, :confirm => 'Are you sure?', :method => :delete, :class => 'admin'%>
						</dd>
					<% end %>

			<% end %>  
			</ul>
			<div><%= link_to "View All Announcements...", events_path(:t=>'News'), :class=>'foot' %></div>
	<% end %>
	<% if @events.any?%>
		<h2>Upcoming Events</h2>		
			<% @events.each do |event| %>
			<div class="eventItem <%= cycle('odd','even') %>">
				<%= link_to event_path(event) do %>
					<span class="eventDate"><%= event.start_date.to_date.to_s(:long) %></span> - <%= event.title %><br />
					<div class="eventBlurb"><%= event.blurb %></div><br />
				<% end %>
			</div> <!-- eventItem -->
			<% end %>
		<div><%= link_to "View All Events...", events_path, :class=>'foot' %></div>
	<% end %>

</div><!-- end middleCol -->
<div id="rightCol">
	<% unless @showcase.nil? %>
	<div class="contentBox1_holder">
		<div class="contentBox1_head">
			<div class="contentBox1_title">COUNTY SHOWCASE</div>
		</div>
		<div class="contentBox1_body">
			<h2><%= link_to @showcase.title, @showcase, :class => 'title' %></h2>
			<%= link_to image_tag (@showcase.photo.url(:medium),  :alt  => @showcase.title, :class => 'imageshadow'), @showcase if @showcase.photo_file_name %>
			<p><%== @showcase.blurb %></p> 
			<div class="article" style="font-size:small;"><%= link_to 'Read more', @showcase, :class => 'foot'%></div>
		</div>
		<div class="contentBox1_foot"></div>
	</div><!--contentBox1 END-->
	<% end %>
	<div class="resources">
		<h2>Featured Resources</h2>
		
		 <%= render :partial => "resources/resource_list" %>
		<div><%= link_to "View All Resources...", resources_path, :class=>'foot' %></div>
	</div>
</div><!-- end rightCol -->