config/routes.rb
Cob::Application.routes.draw do
  resources :animals

  mount Ckeditor::Engine => '/ckeditor'

	resources "users"
  
  resources "user_sessions"
  
  resources "events"
  
  resources :departments do
    collection do 
      post :sort
    end
    resources :contacts
  end
  
  resources :resources do
    collection do 
      post :sort
    end
  end
  
  resources "rescats"
  
  match 'new_contact' =>  'contact_us#new', :conditions => { :method => :get }
  resources :contact_us, :only => [:new, :create]

  resources :faqs do
    collection do
      post :sort
    end
  end

  resources "faq_categories"
  
  resources "showcase_medias"
  resources "showcase_images"
  
  resources :showcases do
    collection do 
      post :sort
    end
    resources :showcase_images
    resources :showcase_medias
  end

  	match 'login' => "user_sessions#new",      :as => :login
  	match 'logout' => "user_sessions#destroy", :as => :logout
	  
	 	root :to => "dash#index"

end

app/models/animal.rb
class Animal < ActiveRecord::Base
 has_attached_file :pic, :styles => { :tiny => "36x36#", :small => "72x72#", :medium => "190"}
   attr_accessible :ac_id, :adoptable, :age, :arrival_date, :breed, :description, :final_date, :location, :pic, :release_date, :sex, :species
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_attached_file :photo, :styles => { :tiny => "25x25#", :small => "72x72#", :medium => "100x111>", :large => "300x300>"}
	belongs_to :department
	
	acts_as_list :scope => :department
	
	attr_accessible :title, :lastname, :firstname, :email, :photo

end

app/models/contact_us.rb
class ContactUs

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  validates_presence_of :name, :message, :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  

  attr_accessor :name, :email, :message, :department_id

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end
end

app/models/department.rb
class Department < ActiveRecord::Base
	has_many :events
	has_many :faqs
	has_and_belongs_to_many :resources
	has_many :contacts
	has_and_belongs_to_many :users
  has_attached_file :pic, :styles => { :tiny => "25x25#", :small => "72x72#", :medium => "190"}
	attr_accessible :dept_fax, :description, :dept_name, :dept_email, :dept_location, :dept_mailing, :dept_phone, :dept_hours, :pic
	validates_presence_of :dept_name
	
	def self.get_contacts(dept)
		dept.contacts.find(:all, :order=>:position)
	end

end

app/models/event.rb
class Event < ActiveRecord::Base
 	belongs_to :department
 	attr_accessible :event_type, :start_date, :end_date, :title, :blurb, :description, :url, :department_id, :placement
 	
 	scope :department, where("placement = 'department' or placement = 'both'")
 	scope :home, where("placement = 'home' or placement = 'both'")
  scope :upcoming, where("end_date >= '#{Date.today}'").order('start_date asc')
  scope :news_type, where("event_type='News' AND start_date<='#{Date.today}'")
  scope :event_type, where("event_type='Event'")
 	
  def	self.find_for_home(event_type,order)
   	if event_type
   		this_condition = " AND event_type='#{event_type}'"
   		if event_type == 'News'
   			this_condition= "AND start_date<='#{Date.today}' " + this_condition
   		end
   	end
   	find(:all, :limit=>6, :order=>'start_date '+ order, :conditions=>"end_date >= '#{Date.today}' #{this_condition}" )
   end

   def	self.find_for_council(event_type)
    	if event_type
    		this_condition = " AND event_type='#{event_type}'"
    	end
    	find(:all, :limit=>6, :order=>'start_date ASC', :conditions=>"end_date >= '#{Date.today}' AND department_id=2 #{this_condition}" )
    end

end

app/models/faq.rb
class Faq < ActiveRecord::Base
	validates_presence_of :answer, :question 
	has_and_belongs_to_many :faq_categories
	belongs_to :department
	attr_accessible :featured, :url, :question, :answer, :department_id, :faq_category_ids
	acts_as_list
	
  include PgSearch
  pg_search_scope :search, :against => [:question, :answer], 
    :using  => {:tsearch  => {:dictionary => "english"}}
	
   	def self.text_search(query)
   	  if query.present?
        search(query)
      else
        scoped
      end
   	end
  
    # def self.search(search)
    #  if search
    #     search = search.to_s.downcase
    #     where(['lower(question) LIKE ? OR lower(answer) LIKE ?', "%#{search}%", "%#{search}%"]).order('position ASC')
    #   end
    # end

	def self.find_for_home
		where('featured = ?',true).order(:position)
	end

end

app/models/faq_category.rb
class FaqCategory < ActiveRecord::Base
	has_and_belongs_to_many :faqs, :order=>"position ASC"
	attr_accessible :category
end

app/models/rescat.rb
class Rescat < ActiveRecord::Base
  has_and_belongs_to_many :resources, :order=>"position asc, resource_type ASC, title asc"
	validates_presence_of :category
	attr_accessible :category, :blurb

end

app/models/resource.rb
class Resource < ActiveRecord::Base
  has_attached_file :res 
	has_and_belongs_to_many :rescats
	has_and_belongs_to_many :departments, :order=>"dept_name asc"
	
  validates_presence_of :res_file_name, :message => "( Document/URL ) cannot be empty"
  validates_presence_of :title
	acts_as_list
  
 	scope :featured, where(:featured => true)

  attr_accessible :title, :description, :featured, :department_ids, :rescat_ids, :res, :resource_type, :res_file_name
 # this before filter and associated function is supposed to allow the upload of a non-image file
	before_post_process :image?
 
	def image?
		!(res_content_type =~ /^image.*/).nil?
	end
	
  include PgSearch
  pg_search_scope :search, :against => [:title, :description], 
    :using  => {:tsearch  => {:dictionary => "english"}}
	
    # def self.search(search)
    #   if search
    #     search = search.to_s.downcase
    #     where(['lower(title) LIKE ? OR lower(description) LIKE ?', "%#{search}%", "%#{search}%"]).order('position asc')
    #   #else
    #   # find(:all)
    #   end
    # end

   	def self.find_for_home
   		where('featured = ?',true).order(:position).limit(10)
   	end

   	def self.text_search(query)
   	  if query.present?
        search(query)
      else
        scoped
      end
   	end	
end

app/models/showcase.rb
class Showcase < ActiveRecord::Base
  has_attached_file :photo, :styles => { :tiny => "25x25#", :small => "72x72#", :medium => "150x150>", :large => "300x300>"}
  has_many :showcase_images, :order => :position
  has_many :showcase_medias
  validates_presence_of :title
  
  attr_accessible :title, :blurb, :published, :sidebar, :article, :publish_date, :photo

  scope :published, where(:published => true).order('publish_date desc')
  def	self.find_for_home
  	#find(:all, :limit=>1, :order=>'publish_date desc', :conditions=>"published = 'true'" )
  	where("published= ?", true).limit(1).order('publish_date desc')
  end
end

app/models/showcase_image.rb
class ShowcaseImage < ActiveRecord::Base
  has_attached_file :photo, :styles => { :tiny => "25x25#", :small => "72x72#", :medium => "150x150>"}
  belongs_to :showcase
  validates_presence_of :photo_file_name
  
  acts_as_list :scope => :showcase
  
  attr_accessible :photo, :caption
end

app/models/showcase_media.rb
class ShowcaseMedia < ActiveRecord::Base
  has_attached_file :media
  belongs_to :showcase
  validates_presence_of :media_file_name
  
  attr_accessible :media, :caption
 # this before filter and associated function is supposed to allow the upload of a non-image file
	before_post_process :image?
 
	def image?
		!(media_content_type =~ /^image.*/).nil?
	end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_and_belongs_to_many :departments
	acts_as_authentic
	attr_accessible :admin_level, :name, :password_confirmation, :login, :password, :department_ids
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dash_helper.rb
module DashHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/rescats_helper.rb
module RescatsHelper
end

app/views/resources/_form.html.erb
<%= form_for(@resource, :html => { :multipart => true }) do |f| %>
<div id="middleCol">
	<h1>New/Update Resource</h1>  
<% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% if !@resource.resource_type # only show for new items %>
<div class="field">
  <%= f.label :resource_type %><br />
  <label style="margin-right:20px;"><%= radio_button("resource", "resource_type", "Page", :checked => true, :onclick => "changeContent('3');")  %> Page </label>
  <label style="margin-right:20px;"><%= radio_button("resource", "resource_type", "Document", :onclick => "changeContent('1');")  %> Document </label>
  <label><%= radio_button("resource", "resource_type", "Link", :onclick => "changeContent('2');")  %> Link </label>
</div>
	<% end %>
  <br />
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, :size=> 40 %>
  </div><br />
  <div class="field">
    <%= f.check_box :featured %> <%= f.label :featured, "Feature on County Home Page" %>
  </div><br />
	<div id="content_area">
		<% if @resource.resource_type == 'Link' %>
			<div class="field">
					<%= f.label :res_file_name, "URL" %>  
					<%= f.text_field :res_file_name, :size=> 80 %>
					<span class="instructions"> e.g. http://www.amazon.com</span>
			</div>		
		<% elsif @resource.resource_type == 'Document' %>
			<div class="field">
					<% if @resource.res_file_name %>
						<%= link_to image_tag('news_icon_sm.gif', :border => '0') +  " View Document", @resource.res.url, :class=>'foot' %>
						<br />
					<% end %>
					<%= f.label :res, "Upload New Document" %>  
					<%= f.file_field :res %>  
			</div>
		<% else %>
			<%= f.hidden_field :res_file_name, :value=>"Text" %>
		<% end %>
	</div><br />
	<div class="field">
		 <%= f.label :description %><br />
	   	<%= f.cktext_area :description, :toolbar=>'Basic2', :width=>'350px', :height=>'300px' %>
	</div><br />
  <div class="actions">
    <%= f.submit %>
	<p>
	<%= link_to 'Cancel', resources_path, :class=>'admin' %>
  	</p>
</div>
</div><!-- middleCol -->
<div id="rightCol">
	<h1> Select Categories</h1>
		<div style="padding-left: 10px;">
	 <% for rescat in @rescats %>  
			 <div>  
				 <label><%= check_box_tag "resource[rescat_ids][]", rescat.id, @resource.rescats.include?(rescat) %>  
				 <%= rescat.category %>  </label>
			 </div>  
	 <% end %>
	<br />
	 </div>
		<h1> Select Departments</h1>
			<div style="padding-left: 10px;">
		 <% for department in @departments %>  
				 <div>  
					 <label><%= check_box_tag "resource[department_ids][]", department.id, @resource.departments.include?(department) %>  
					 <%= department.dept_name %>  </label>
				 </div>  
		 <% end %>
		</div>
</div>	
<% end %>

app/views/resources/_home_resources.html.erb
		 <dl id="resources" class="resourceList homelist">
		<% @resources.each do |resource| %>  
			<div  id="resource_<%= resource.id %>">
				<% if resource.resource_type == 'Document' %>
					<dt class="<%= get_icon(resource.res_content_type) %>"><%= link_to resource.title, resource.res.url, :title => "Download #{resource.res_file_name} ~#{resource.res_file_size/1000} KB", :target => '_blank' %></dt>
				<% elsif resource.resource_type == 'Link' %>
					<dt class="link" id="item_<%= resource.id %>"><%= link_to resource.title, format_url(resource.res_file_name), :target => '_blank' %></dt>
				<% else %>
					<dt class="page" id="item_<%= resource.id %>"><%= link_to resource.title, resource_path(resource) %></dt>			
				<% end %>
				<% if admin? %>
					<dd> <%= link_to	'Edit', edit_resource_path(resource), :class => 'admin' %>  
					<%= link_to 'Delete', resource, :confirm => 'Are you sure?', :method => :delete, :class => 'admin'%></dd>
				<% end %>
			</div>

		<% end %>
		</dl>

app/views/resources/_resource_list.html.erb
		 <dl id="resources" class="resourceList">
		<% @resources.each do |resource| %>  
			<div  id="resource_<%= resource.id %>">
				<% if resource.resource_type == 'Document' %>
					<dt class="<%= get_icon(resource.res_content_type) %>"><%= link_to resource.title, resource.res.url, :title => "Download #{resource.res_file_name} ~#{resource.res_file_size/1000} KB", :target => '_blank' %></dt>
					<% if resource.description.size %><dd><%= strip_tags(resource.description) %></dd><% end %>
				<% elsif resource.resource_type == 'Link' %>
					<dt class="link" id="item_<%= resource.id %>"><%= link_to resource.title, format_url(resource.res_file_name), :target => '_blank' %></dt>
					<% if resource.description.size %><dd><%= strip_tags(resource.description) %></dd><% end %>
				<% else %>
					<dt class="page" id="item_<%= resource.id %>"><%= link_to resource.title, resource_path(resource) %></dt>			
				<% end %>
				<% if admin? %>
					<dd><span class="handle" style="<%= @cursor_style %>">DRAG</span> <%= link_to	'Edit', edit_resource_path(resource), :class => 'admin' %>  
					<%= link_to 'Delete', resource, :confirm => 'Are you sure?', :method => :delete, :class => 'admin'%></dd>
				<% end %>
			</div>

		<% end %>
		</dl>
<% content_for :javascript  do %>
  <%= javascript_tag do %>
    // Sorting the list

    $(document).ready(function(){
      $('#resources').sortable({
        axis: 'y',
        dropOnEmpty: false,
        handle: '.handle',
        cursor: 'crosshair',
        items: 'div',
        opacity: 0.4,
        scroll: true,
        update: function(){
          $.ajax({
            type: 'post',
            data: $('#resources').sortable('serialize'),
            dataType: 'script',
            complete: function(request){
              $('#resources').effect('highlight');
              },
            url: '/resources/sort'})
          }
        });
      });
  <% end %>
<% end %>

app/views/resources/edit.html.erb
<%= render 'form' %>

app/views/resources/index.html.erb
<div id="middleCol">
<h1>Resources</h1>
<% if admin? %>
	<%= link_to 'New Resource', new_resource_path, :class => 'admin' %> 
	<%= link_to 'Categories', rescats_path, :class => 'admin' %>
<% end %>
	<div>
		<%= form_tag resources_path, :method => 'get' do %>
	  <p>
	    <label class="instructions"> Keyword Search</label><br />
	    <%= text_field_tag :query, params[:query] %>
	    <%= submit_tag "Search", :name => nil %>
	  </p>
		<% end %>
		<p class="instructions">Enter a search term, such as <tt><big>permit</biG></tt> or <tt><big>schedule</biG></tt>
		</p>
	</div>

	<h2 class="monthDivider boxshadow"><%= @title_text %></h2>
	<div class="instructions"><%== @blurb %> </div>
	 <%= render :partial => "resource_list" %>
</div>

<div id="rightCol" style="margin-top:0;">
	<p><%= link_to "View Featured", resources_path, :class => 'foot sidebar'%></p>

	<h3 class="title">Resource Categories</h3>
	<span class="instructions">Click to Browse by Category</span>
			<ul class="pineapple">
			<% @rescats.each do |cat| %>
				<% unless cat.resources.empty? %>
				<li><%= link_to cat.category, :action=>:index, :controller=>:resources, :cat=>cat %></li>
				<% end %>
			<% end %>
			</ul>
		<p><%= link_to 'View Uncategorized', {:action=>:index, :controller=>:resources, :all=>1},:class => 'admin' if admin? %></p>
</div>

app/views/resources/new.html.erb
<%= render 'form' %>

app/views/resources/show.html.erb
<div id="middleCol">
<h1>Resource</h1>
<h2>  <%== @resource.title %></h2>
<div class="description">
  <%== @resource.description %>
</div>
<% if admin? %>
	<dl class="resourceList">
		<% if @resource.resource_type == 'Document' %>
			<dt class="<%= get_icon(@resource.res_content_type) %>"><%= link_to @resource.title, @resource.res.url, :title => "Download #{@resource.res_file_name}", :target => '_blank' %> <span class="list_date">~<%= @resource.res_file_size/1000 %> KB</span></dt>
			<% if @resource.description.size %><dd><%== @resource.description %></dd><% end %>
		<% elsif @resource.resource_type == 'Link' %>
			<dt class="link" id="item_<%= @resource.id %>"><%= link_to @resource.title, format_url(@resource.res_file_name), :target => '_blank' %></dt>
			<% if @resource.description.size %><dd><%== @resource.description %></dd><% end %>
		<% end %>
	</dl>

	<p>
		<b>Featured:</b>
		<%=h @resource.featured %>
	</p>



	<%= link_to 'Edit', edit_resource_path(@resource), :class=>'admin' %> 
	<%= link_to 'Back', resources_path, :class=>'admin' %>
<% end %>
</div>